### ISSUE TITLE
Moving a node to the end

### ISSUE THREAD

**Issue by giorgio93p** [giorgio93p/book-embeddings#2]
Program crashes when we try to move a node to the last position.

**Comment by kosniaz** [comment]
olo gkrinia eisai

2015-08-29 16:46 GMT+03:00 Giorgio P notifications@github.com:

> Program crashes when we try to move a node after the last one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/giorgio93p/book-embeddings/issues/2.

## 

Kosmas Z. Palios, Undergraduate Student     |
National Technical University of Athens     | Phone Number: +30-210-9811266
School of Electrical & Computer Engineering | E-mail: kosmas.palios@gmail.com
Student Registration Number: 03111011       |
